# Run:
#    conda env create --file environment.yml
# Run (overrides the environment name):
#    conda env create --file environment.yml --name your_env_name
# Customized environment "Python 3.7"
name: py37
channels:
  # Anaconda
  - anaconda
  # Conda forge distribution
  # https://conda-forge.org
  - conda-forge
  # Default distribution from Continuum/Anaconda
  - default
dependencies:
  - anaconda
  - python=3.7

